#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026 Nathan M. Fraske
#
# Stop hook — WSL-EPHEMERAL STATE POLICY enforcement, end half (owner directive 2026-06-14).
#
# Every session end: refresh the durable in-tree memory mirror, regenerate the agent handoff, and COMMIT +
# PUSH the handoff + memory + the root tracking files (HANDOFFS/FOLLOWUPS/TODOS) to the dedicated
# `ops/agent-handoff` branch on the remote. This guarantees the cross-session state can never again exist
# ONLY on the (ephemeral) WSL volume — the failure mode that silently loses uncommitted work on a WSL wipe.
#
# NON-DISRUPTIVE BY CONSTRUCTION: it never checks out, never touches HEAD or the normal index. The commit is
# assembled with git plumbing (hash-object -> a temp index -> commit-tree) and pushed straight to the branch
# ref. The ONLY working-tree write is refreshing the agent's own durable memory mirror (.claude/memory/*.md,
# already git-tracked). Fail-soft + time-bounded: a Stop hook must never block or fail the session.
set -uo pipefail
exec 2>/dev/null            # never leak noise onto the session's Stop path
cat >/dev/null || true      # drain the hook JSON on stdin; we don't need it

ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
BRANCH="ops/agent-handoff"
cd "$ROOT" 2>/dev/null || exit 0
git rev-parse --git-dir >/dev/null 2>&1 || exit 0   # not a git repo -> nothing to do

# Resolve the persistent-memory dir (same derivation as session-start.sh: map '/._' -> '-').
memdir="$HOME/.claude/projects/$(echo "$ROOT" | tr '/._' '---')/memory"
[ -d "$memdir" ] || memdir="$HOME/.claude/projects/-home-nathan-CEC-AutoDiagnoser/memory"

# --- refresh the DURABLE in-tree memory mirror (WSL-ephemeral state policy) ---------------------------
# Mirror the live ~/.claude memory *.md into the committed, git-tracked .claude/memory/ so the versioned
# copy never drifts stale. Plain file copy: no HEAD/index touch; the next normal commit carries them. The
# off-tree side-branch push below is the wipe-proof copy; this in-tree mirror is what the start hook seeds
# from on a fresh clone.
committed="$ROOT/.claude/memory"
mkdir -p "$committed" 2>/dev/null || true
if [ -d "$memdir" ]; then
  for f in "$memdir"/*.md; do
    [ -e "$f" ] || continue
    cp "$f" "$committed/$(basename "$f")" 2>/dev/null || true
  done
fi

# Optional: pull in a survives-WSL bot PAT if the owner ever adds one; else fall back to the gh credential.
# shellcheck disable=SC1091
[ -f "$ROOT/ops/secrets/load-secrets.sh" ] && . "$ROOT/ops/secrets/load-secrets.sh" 2>/dev/null || true

run() { timeout 60 "$@"; }   # hard cap; the session never waits on git/network

# A pristine post-WSL-wipe clone has NO git identity configured, and `git commit-tree` REFUSES to build a
# commit without one ("empty ident name") — which would silently kill the durability push. Supply an
# identity via env (overrides config for this process only): the configured identity if present, else a
# stable bot fallback. This is the exact gotcha that the WSL-ephemeral policy exists to survive.
_id_name="$(git config user.name 2>/dev/null || true)";  [ -n "$_id_name" ]  || _id_name="cec-agent-handoff[bot]"
_id_email="$(git config user.email 2>/dev/null || true)"; [ -n "$_id_email" ] || _id_email="agent-handoff@cec.direct"
export GIT_AUTHOR_NAME="$_id_name" GIT_AUTHOR_EMAIL="$_id_email" \
       GIT_COMMITTER_NAME="$_id_name" GIT_COMMITTER_EMAIL="$_id_email"

# --- 1) generate the handoff into a TEMP file (never written to the working tree) --------------------
tmp_handoff="$(mktemp)"; trap 'rm -f "$tmp_handoff"' EXIT
{
  echo "# Agent handoff — $(date -u '+%Y-%m-%d %H:%M:%SZ')"
  echo
  echo "_Auto-generated by .claude/hooks/session-end.sh and pushed to \`$BRANCH\`._"
  echo "_Per the WSL-ephemeral state policy: this is the durable, remote copy of the cross-session state._"
  echo
  echo "## Repo state"
  echo '```'
  echo "branch:  $(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
  echo "HEAD:    $(git log -1 --oneline 2>/dev/null)"
  echo "status:  $(git status --porcelain 2>/dev/null | wc -l) uncommitted path(s)"
  echo '```'
  echo
  echo "### Recent commits"
  echo '```'
  git log --oneline -12 2>/dev/null
  echo '```'
  echo
  echo "### Working-tree changes"
  echo '```'
  git status --short 2>/dev/null | head -40
  echo '```'
  echo
  echo "## Local inference / broker"
  if curl -fsS --max-time 3 "http://localhost:${CEC_BROKER_PORT:-8080}/v1/models" 2>/dev/null; then :; else
    echo "(no local OpenAI-compatible endpoint reachable on :${CEC_BROKER_PORT:-8080})"
  fi
  echo
  echo "## Cross-agent baton (HANDOFFS.md)"
  [ -f "$ROOT/HANDOFFS.md" ] && { echo; cat "$ROOT/HANDOFFS.md"; } || echo "(no HANDOFFS.md)"
  echo
  echo "## Persistent-memory snapshot"
  [ -f "$memdir/current-work-handoff.md" ] && { echo "### current-work-handoff.md"; echo; cat "$memdir/current-work-handoff.md"; }
  [ -f "$memdir/MEMORY.md" ] && { echo; echo "### MEMORY.md (index)"; echo; cat "$memdir/MEMORY.md"; }
} > "$tmp_handoff"

# --- 2) assemble a commit with plumbing, on top of the remote branch (no checkout) -------------------
run git fetch -q origin "$BRANCH" 2>/dev/null || true
tmpidx="$(mktemp)"; export GIT_INDEX_FILE="$tmpidx"
trap 'rm -f "$tmp_handoff" "$tmpidx"' EXIT
parent="$(git rev-parse -q --verify "refs/remotes/origin/$BRANCH" 2>/dev/null || true)"
if [ -n "$parent" ]; then git read-tree "$parent" 2>/dev/null || git read-tree --empty
else git read-tree --empty; fi

add_blob() {  # add_blob <src-file> <path-in-tree>
  [ -f "$1" ] || return 0
  local blob; blob="$(git hash-object -w "$1" 2>/dev/null)" || return 0
  git update-index --add --cacheinfo "100644,$blob,$2" 2>/dev/null || true
}
add_blob "$tmp_handoff" "docs/agent/handoff.md"
# The root tracking files: durable even when uncommitted on the main branch (the WSL-wipe failure mode).
for t in HANDOFFS.md FOLLOWUPS.md TODOS.md; do add_blob "$ROOT/$t" "$t"; done
# The persistent-memory mirror.
for f in "$memdir"/*.md; do
  [ -e "$f" ] || continue
  add_blob "$f" ".claude/memory/$(basename "$f")"
done

tree="$(git write-tree 2>/dev/null)" || exit 0
[ -n "$tree" ] || exit 0
# Skip an empty no-op commit if nothing changed vs the parent.
if [ -n "$parent" ] && [ "$tree" = "$(git rev-parse "$parent^{tree}" 2>/dev/null)" ]; then exit 0; fi
msg="agent handoff $(date -u '+%Y-%m-%dT%H:%M:%SZ') [session-end hook]"
if [ -n "$parent" ]; then commit="$(git commit-tree "$tree" -p "$parent" -m "$msg" 2>/dev/null)"
else commit="$(git commit-tree "$tree" -m "$msg" 2>/dev/null)"; fi
[ -n "$commit" ] || exit 0

# --- 3) push to the branch ref. Prefer a survives-WSL PAT if present; else gh-credential push. --------
unset GIT_INDEX_FILE
if [ -n "${CEC_BOT_PAT:-}" ]; then
  url="$(git remote get-url origin | sed -E "s#https://([^@/]*@)?github.com#https://x-access-token:${CEC_BOT_PAT}@github.com#")"
  run git push -q "$url" "$commit:refs/heads/$BRANCH" 2>/dev/null || true
else
  run git push -q origin "$commit:refs/heads/$BRANCH" 2>/dev/null || true
fi
exit 0
