use serde::{Deserialize, Serialize};

use crate::plan::Plan;

/// Where a candidate plan came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CandidateSource {
    /// Generated by a model with no corpus context (cold start).
    #[default]
    ColdModel,
    /// Generated by a model primed with corpus matches.
    CorpusPrimed,
    /// Authored or edited by a human operator.
    Human,
}

/// A proposed remediation produced for the judge panel to score.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Candidate {
    /// The plan to evaluate.
    pub plan: Plan,
    /// Why the generator believes this plan addresses the fault.
    pub rationale: String,
    /// Provenance of the candidate.
    pub source: CandidateSource,
}

impl Candidate {
    /// Wrap a plan with its rationale and source.
    pub fn new(plan: Plan, rationale: impl Into<String>, source: CandidateSource) -> Self {
        Self {
            plan,
            rationale: rationale.into(),
            source,
        }
    }
}
