use serde::{Deserialize, Serialize};

use crate::plan::Plan;
use crate::Prose;

/// Where a candidate plan came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CandidateSource {
    /// Generated by a model with no corpus context (cold start).
    #[default]
    ColdModel,
    /// Reasoned from a curated knowledge REPERTOIRE (vendor KB, documented
    /// procedures, the driver library) rather than guessed cold — grounded in
    /// real knowledge but NOT authored in the corpus for this signature at this
    /// config class. It ranks above a cold guess and below a confirmed
    /// precedent, and is surfaced as "confident but unproven": a corpus row it
    /// earns comes only through the gate (a machine- or human-verified outcome),
    /// never from the repertoire directly. This is the read-side tier that lets
    /// the engine expand its own knowledge — a `Repertoire` fix that runs and
    /// verifies clean earns a `VerifierConfirmed` row with no human in the loop.
    Repertoire,
    /// Generated by a model primed with corpus matches.
    CorpusPrimed,
    /// Authored or edited by a human operator.
    Human,
}

/// A proposed remediation produced for the judge panel to score.
///
/// An **in-flight** type: `rationale` is free-text prose (a model often echoes
/// the request into it), so `Candidate` has no `Serialize` — `to_string(&cand)`
/// or `json!({"why": c.rationale})` is a compile error. Only the de-identified
/// action vocabulary of its plan reaches a sink (see `diagnose_envelope`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Candidate {
    /// The plan to evaluate.
    pub plan: Plan,
    /// Why the generator believes this plan addresses the fault. Free-text
    /// prose (a model often echoes the request into it), so it is [`Prose`]:
    /// no `Serialize`/`Display`, and it never reaches the `--json`/API envelope.
    pub rationale: Prose,
    /// Provenance of the candidate.
    pub source: CandidateSource,
}

impl Candidate {
    /// Wrap a plan with its rationale and source.
    pub fn new(plan: Plan, rationale: impl Into<Prose>, source: CandidateSource) -> Self {
        Self {
            plan,
            rationale: rationale.into(),
            source,
        }
    }
}
